name: pirate-quest # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Pirate Plunder Quest
summary: Sail the seas for fame and fortune.
description: Assemble your pirate crew, raid enemy ships, and uncover buried treasures in this ultimate sea adventure.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pirate-quest:
    command: bin/pirate-quest-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  pirate-quest:
    plugin: dump
    source: .
    organize:
      pirate-quest-bin: bin/
